### ISSUE TITLE
PHPstorm stubs

### ISSUE THREAD

**Issue by mjpvandenberg** [php-ds/ext-ds#128]
Jetbrains offers a repository for PHP extension stubs used in PHPstorm:
https://github.com/jetbrains/phpstorm-stubs
I expect that contributing the DS stubs there would help a significant portion of your users, and would (somewhat) relieve the need for maintaining the polyfill (#92)

**Comment by rtheunissen** [comment]
I had no idea. :open_mouth: 

I'll request that ds and decimal be added, thank you. :sparkles:

**Comment by edmondscommerce** [comment]
looks like this hasn't happened yet, agreed it would great if it could be organised

**Comment by hopeseekr** [comment]
I've picked up the mantle and will be developing it right now. I've done this sort of stuff in the past.

I'll also (::gasp::) create the first Unit test in this project that will instantly check and confirm that the PhpStorm stub is up-to-date and current (using reflection).

it's actually pretty fun project for me. 

I'll create a PR against the polyfill project and stick it in the root directory of the project, entitled "phpstorm-stub.php". It is a single file that contains all of the classes with their public constants, properties and methods.

**Comment by hopeseekr** [comment]
Great use of my first 2 1/2 hours on this beautiful Saturday! 

Thanks for such an awesome project, guys!! The datatypes of HackLang that seemingly inspired this project were my #1 reason for flipping over to that project, back when they were attempting to take on the PHP leadership mantle a few years ago.

I'm so happy I found this project today and can once again use Collections and actual functional data structures in *actual* PHP for the first time, without the idiosyncrasies of the unmaintained SPL.

Cheers!

**Comment by enumag** [comment]
This can be closed. PHPStorm has stubs for this extension now.
https://github.com/JetBrains/phpstorm-stubs/blob/master/ds/ds.php
