### ISSUE TITLE
Provide `each` for iteration over collections

### ISSUE THREAD

**Issue by zlikavac32** [php-ds/ext-ds#135]
Hi,

Thank you for this great library.

One thing that I do miss is having an `each` method that would just iterate over a collection.

I've seen these three issues:

https://github.com/php-ds/ext-ds/issues/51
https://github.com/php-ds/ext-ds/issues/50
https://github.com/php-ds/ext-ds/issues/49

And was wondering why where they closed and are there any plans for such functionality?

Would a PR for that functionality be an option?

**Comment by rtheunissen** [comment]
A method like `each` is the responsibility of an iterator library, ie. `function each(iterable $iter): Iterator`. There is currently no plan to implement `each` in 1.x or 2.0
