### ISSUE TITLE
FreeBSD support?

### ISSUE THREAD

**Issue by eqmaz** [php-ds/ext-ds#142]
Hi,

Just wondering what is the current support for (or has this been tested with) PHP on FreeBSD? I heard there were some issues?

All the best

**Comment by rtheunissen** [comment]
I am not aware of any issues. What have you heard?

**Comment by oschonrock** [comment]
Is it just there that is no port for it? Has it been suggested to the php/pecl port maintainer? 

Also hoping to use this excellent extension on FreeBSD on a "big data" App, but reluctant without an official port. 

Suspect that the code will work (nothing unusual or kernel/thread specific?), could just a matter of creating/testing/maintaining the port?

Not an experienced port maintainer, but can assist in testing. We have a range of FreeBSD11.2/12 dev/production machines and build our own packages from ports using poudriere.

**Comment by rtheunissen** [comment]
I have no understanding of FreeBSD but I am happy to support in any way I can. This extension does not have any library dependencies or quirks - should be easy to manage.

**Comment by oschonrock** [comment]
OK, as a first step, I have dropped an email to a couple of the active pecl port maintainers. If they know of no specific issues, then hopefully this can be addressed. 

Will update here...

**Comment by sunpoet** [comment]
It works just fine. I've added it to the ports tree as [devel/pecl-ds](https://svnweb.freebsd.org/changeset/ports/506449).

**Comment by oschonrock** [comment]
Nice one @sunpoet !

**Comment by oschonrock** [comment]
Confirm compiled pkg from port with our local poudriere (FBSD 11.2 php 7.2 flavour). Others can just install the package with:

# pkg install php72-pecl-ds    (or similar depending on your php version)

All works great. Thank you everyone. 
Can close / resolved?
