### ISSUE TITLE
PHP 7.4 support (is the project still alive?)

### ISSUE THREAD

**Issue by alumarcu** [php-ds/ext-ds#146]
As I don't see much recent activity on the project, I'm wondering if are there any efforts in progress to make the extension available for PHP7.4, or if the project is dead?

**Comment by rtheunissen** [comment]
> As I don't see much recent activity on the project

I have been studying for and working on both the next minor and major release, so the project is very active on the R&D side even though there haven't been any changes to master in a while. Definitely not dead. 

> I'm wondering if are there any efforts in progress to make the extension available for PHP7.4

It already compiles for 7.4, so as soon as the release is available it will be available for 7.4 through PECL. Tests are already running on 7.4, might need an update though, not sure if that snapshot is still relevant. https://travis-ci.org/php-ds/ext-ds/jobs/599053920
