### ISSUE TITLE
Segmentation fault when pushing multiple times after a map()

### ISSUE THREAD

**Issue by jruillier-afidium** [php-ds/ext-ds#154]
First, thanks for bringing Datastructures to PHP 👍 

When I run this code with the ext-ds extension enabled, I get a Segmentation Fault on macOS.
When the extension is disbaled and the polyfill is used, no error occurs.

I was getting Segmentation Faults on an enterprise app, running a similar code, running on Debian 10.3. Unfortunately this code does not reproduce the problem on Debian :-/

I've been testing with PHP 7.3.21 and 7.4.9, and with ext-ds 1.2.9, running on Debian 10.3 and macOs 10.15.5

```
<?php

$vector = new \Ds\Vector();
$vector->push(new DateTime());
$sequence = $vector->map(function (DateTime $_dateTime) { return $_dateTime->format(DateTime::ISO8601);});

$sequence->push(new DateTime());
$sequence->push(new DateTime());
	
$sequence->push(new DateTime());
$sequence->push(new DateTime());

$sequence->push(new DateTime());
$sequence->push(new DateTime());
	
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());
$sequence->push(new DateTime());

echo 'done';
```

I get the same segfault on an enterprise project... so we stick to the polyfill for now.

**Comment by rtheunissen** [comment]
This and #153 has been fixed on master, working on a release now.

**Comment by enumag** [comment]
@rtheunissen Thank you!

**Comment by enumag** [comment]
@rtheunissen How is the release going? Is the process to make a new release complicated?

**Comment by rtheunissen** [comment]
@enumag I apologize, it actually is very easy to release a new version. I built on PHP 8 and the build failed, so I was hoping to fix that as part of this release. If I can't get that done by the end of the weekend I'll release what's on master today.

**Comment by rtheunissen** [comment]
There are a few other bugfixes to release also. It mostly involves making sure the polyfill and test are in sync, writing the release notes, and creating the archive.

**Comment by enumag** [comment]
I see. Yeah, having PHP 8 working would be preferable. I intent to try it soon-ish. Thanks for letting me know!

**Comment by enumag** [comment]
@rtheunissen Any progress? :-)

**Comment by rtheunissen** [comment]
@enumag I finally mustered some energy to get this done, along with a few other fixes. Released as 1.3.0 :tada:

**Comment by enumag** [comment]
Thank you!! 🎉🎉

**Comment by brettgoss** [comment]
I ran into this bug recently in a project using the 1.2.9 version of php-ds (which ships with Ubuntu 20.04), and noticed it wasn't mentioned in the changelog either [here](https://github.com/php-ds/ext-ds/blob/master/CHANGELOG.md) or in the [pecl changelog](https://pecl.php.net/package-changelog.php?package=ds). 

Is it worth updating the changelog to include a note about this bugfix and others, up until the latest 1.5.0 release? I'm happy to open a PR to add a note about this fix if that would be helpful.
