### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by mxr576** [php-ds/ext-ds#155]
Hi,

First of all, thanks for this awesome extension :)

Second, is this project still maintained? Because I cannot decide that based on the number (and age of) open issues and commit activety in this repo and the companion [polyfill](https://github.com/php-ds/polyfill).

**Comment by rtheunissen** [comment]
Hi @mxr576 yes, absolutely still maintained. I have a long list of things I want to work on here, but being a solo maintainer makes it difficult to consistently make small improvements. My intention for today is to fix the segmentation fault issues and any PHP 8 compatibility problems. 

Some of the very old open issues were discussions that may now be sidelined. I'll take a look. 👍

**Comment by mxr576** [comment]
@rtheunissen thanks for the quick answer :) So I am going to use this extension on my project(s) ;)
