### ISSUE TITLE
pecl install on mac with PHP 7.4 error

### ISSUE THREAD

**Issue by flaushi** [php-ds/ext-ds#158]
Hey, I have just upgraded to php 74, getting this now on `pecl install -f ds`

![image](https://user-images.githubusercontent.com/15819451/95105190-131a0480-0737-11eb-91aa-f314a4d46bcd.png)

```
php --version
PHP Warning:  Module 'stats' already loaded in Unknown on line 0

Warning: Module 'stats' already loaded in Unknown on line 0
PHP 7.4.11 (cli) (built: Oct  1 2020 23:30:54) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies
% cc --version
Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
``` 
is ds compatible with 7.4?

Thanks in advance!

**Comment by rtheunissen** [comment]
That looks like an error within php-src itself, how are you attempting to install this?
Definitely supported on 7.4

**Comment by flaushi** [comment]
yup, I had to force-reinstall the developer tools and all php packages (homebrew), then it somehow worked.
