### ISSUE TITLE
Wrong documentation for Set::__construct

### ISSUE THREAD

**Issue by enumag** [php-ds/ext-ds#167]
https://www.php.net/manual/en/ds-set.construct.php

The method is documented as:

```
public Ds\Set::__construct ( mixed ...$values )
```

But it is actually:

```
public Ds\Set::__construct ([ mixed $values ])
```

Also reported here: https://bugs.php.net/bug.php?id=81157

**Comment by cmb69** [comment]
Fixed as https://github.com/php/doc-en/commit/9e3e335d2f2319d11323185445fe91fb40352fe9.

Ticket can be closed.
