### ISSUE TITLE
map method for Set?

### ISSUE THREAD

**Issue by designermonkey** [php-ds/ext-ds#174]
Please excuse my ignorance if that's what this question is (I didn't studdy computer science)...

Is there any reason there isn't a `map` method for a `Set`? `Vector` has it, being a `Sequence`, `Map` has it and is a `Collection` not `Sequence`, so is there a specific reason that `Set` does not, being a `Collection` like `Map`?

**Comment by wells5609** [comment]
What version of `ds` are you using? The `map` method was added to `Set` in v1.2.7.

**Comment by designermonkey** [comment]
Ah ok, thanks for letting me know! The documentation on php.net is incorrect then.

**Comment by rtheunissen** [comment]
> The documentation on php.net is incorrect then

Yes that definitely needs to be updated, I'll create a new issue for that and link this one.
Thanks :+1:
