### ISSUE TITLE
How to make sure extension is used

### ISSUE THREAD

**Issue by flaushi** [php-ds/ext-ds#176]
I use PHP 7.4.
My composer requires 
```
"ext-ds": "^1.2",
```
and also require**d**
```
"php-ds/php-ds": "^1.2",
```
To be honest I didn't even know about this polyfill until I have started searching for the possible source of a memleak I am experiencing.

If I follow the symbols in my code

```
namespace App\Service;
use Ds\Stack;
class MyService {
    public function bla() {
        $stack = new Stack();
```
It lead me to the polyfill. How can I be sure which code was used, native or polyfill?

Side question: any findings about possible memleaks in Stack?
In a long running process I am pushing and popping doctrine entities in it, and although repeatedly clearing the UnitOfWork, my memory usage goes into gigabytes.

Thanks in advance!

**Comment by enumag** [comment]
If extension is installed then extension is used. So if you have it in composer.json and didn't use `--ignore-platform-reqs` you can be sure your code uses the extension. You can also verify it using ReflectionClass - extension classes will have no file.

**Comment by enumag** [comment]
As for memory leak in Stack, try deleting the extension, forcing the polyfill and see if the leak persists. If it disappears then it suggests a leak in this extension. Also check which version of the extension you're using. There were some fixes in 1.3.

**Comment by flaushi** [comment]
Yes I am using version 1.3.0.
I will try to use it without the extension.

**Comment by flaushi** [comment]
I tried and it's **not** ds.
Thanks for your quick and helpful support!

**Comment by enumag** [comment]
you're welcome! good luck with the leak!
