### ISSUE TITLE
Upgrade PECL page to identify homepage

### ISSUE THREAD

**Issue by llaville** [php-ds/ext-ds#205]
Hello,

I think it will be better to identify directly this https://github.com/php-ds/ext-ds URL from http://pecl.php.net/package/ds page, rather than https://github.com/php-ds general page !

WDYT ?

**Comment by rtheunissen** [comment]
I agree! 🤝

**Comment by llaville** [comment]
Did you missed to apply change ?
PECL website still display old url.
