### ISSUE TITLE
Null coalescing operator on Vector make search failed

### ISSUE THREAD

**Issue by josephLaurent** [php-ds/ext-ds#206]
Hello,

I have a strange issue with Vector after accessing element with the Null coalescing operator.

```
$vector = new Vector([5, 6, 7]);

var_dump($vector->contains(5)); // Print true
var_dump($vector->contains(6)); // Print true

$vector[0] ?? null;

var_dump($vector->contains(5)); // Print false !!!
var_dump($vector->contains(6)); // Print true
```

Is this expected ? Can it be fixed ?

Don't hesitate if you need more info and thank you in advance for your help

**Comment by nielsdos** [comment]
This happens because `php_ds_vector_read_dimension` makes a REF from the value when type is not `BP_VAR_R`. So when the type is `BP_VAR_IS` then we see the first element becomes a reference. You can see this when var_dumping:

```
object(Ds\Vector)#1 (3) {
  [0]=>
  &int(5)
  [1]=>
  int(6)
  [2]=>
  int(7)
}
```

To solve this, the code has to check `BP_VAR_IS` too. I'll make a PR.

**Comment by josephLaurent** [comment]
Thank you for the fast implementation :)
