### ISSUE TITLE
ArrayAccess should be explicitly implemented

### ISSUE THREAD

**Issue by rtheunissen** [php-ds/ext-ds#39]
This is so that it's possible to call the array access functions directly, even though no one should ever need to do that.
- [x] Test calling the offset\* functions as well.

**Comment by rtheunissen** [comment]
Added within 01813448166f83b576534fb01f0eb96c8cdf1223

**Comment by castarco** [comment]
It seems that the implementation of this interface on Vector is not documented on the official PHP site ( https://secure.php.net/manual/en/book.ds.php )

**Comment by andrew-demb** [comment]
Hello @rtheunissen.

> Added within [0181344](https://github.com/php-ds/ext-ds/commit/01813448166f83b576534fb01f0eb96c8cdf1223)
I can't find the mentioned commit and these changes in any branch and any mention in changelogs about removing this functionality from the extension.

Is it planned to remove implementing `\ArrayAccess`?
I can create new issue here, or drop implementation of `\ArrayAccess` in polyfill?
https://github.com/php-ds/polyfill/issues/47

**Comment by rtheunissen** [comment]
You mean this commit? https://github.com/php-ds/ext-ds/commit/01813448166f83b576534fb01f0eb96c8cdf1223

We are not removing `ArrayAccess`, I'm sorry but what are you suggesting exactly? Looking at this again it seems like we're not implementing `ArrayAccess` properly.

**Comment by andrew-demb** [comment]
Yes, this commit.

I'm suggested to remove implementing `ArrayAccess` from polyfill, if extension won't provide implementation.
 
Or open issue here instead :)

Thank you.

**Comment by ManuelHirsch** [comment]
FYI - I just tripped over this when developing with the polyfill but having the extension on the test system (fortunately not live!). 

For google, to relate this issue with the error message: "Fatal error: Uncaught Error: Call to undefined method Ds\Vector::getIterator() in ..." and probably all ArrayAccess methods then.

**Comment by dktapps** [comment]
This also causes some issues with static analysers (f.e. phpstan/phpstan#2847)

**Comment by rtheunissen** [comment]
Done and released as part of 1.3.0
